# Generated by Django 4.1.3 on 2022-11-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_influenceur_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='avatar',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='avatar',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
    ]
