# Generated by Django 4.1.3 on 2022-11-27 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entreprise_avatar_influenceur_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_recto', models.FileField(upload_to='identity')),
                ('identity_verso', models.FileField(upload_to='identity')),
                ('aleatoire_number', models.IntegerField(default=0)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='entreprise',
            name='badge_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='badge_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='badge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.badge'),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='badge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.badge'),
        ),
    ]
