# Generated by Django 4.1.3 on 2022-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_badge_entreprise_badge_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
