# Generated by Django 4.1.3 on 2022-12-07 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_entreprise_solicited_influenceur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='solicited_influenceur',
            field=models.ManyToManyField(related_name='influenceursolicite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='influenceur',
            name='solicited_enterprise',
            field=models.ManyToManyField(related_name='entreprisesollicite', to=settings.AUTH_USER_MODEL),
        ),
    ]
