# Generated by Django 4.1.3 on 2022-12-07 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_entreprise_solicited_influenceur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='solicited_influenceur',
        ),
        migrations.RemoveField(
            model_name='influenceur',
            name='solicited_enterprise',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='influenceurs',
            field=models.ManyToManyField(related_name='influenceurs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='enterprises',
            field=models.ManyToManyField(related_name='enterprises', to=settings.AUTH_USER_MODEL),
        ),
    ]
