# Generated by Django 4.1.3 on 2022-12-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_entreprise_solicited_influenceur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='influenceurs',
            field=models.ManyToManyField(related_name='influenceurs', to='core.influenceur'),
        ),
        migrations.AlterField(
            model_name='influenceur',
            name='enterprises',
            field=models.ManyToManyField(related_name='enterprises', to='core.entreprise'),
        ),
    ]
