# Generated by Django 4.1.3 on 2022-12-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_badge_selfie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='influenceur',
            name='places',
            field=models.ManyToManyField(related_name='places', to='core.pays'),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='languages',
            field=models.ManyToManyField(to='core.language'),
        ),
    ]
