# Generated by Django 4.1.3 on 2022-11-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='announces'),
        ),
    ]
