# Generated by Django 4.1.3 on 2022-12-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_entreprise_influenceurs_and_more'),
        ('announce', '0002_announce_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitation',
            name='user',
        ),
        migrations.AddField(
            model_name='solicitation',
            name='influenceur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.influenceur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announce',
            name='Solicitations',
            field=models.ManyToManyField(related_name='solicitations', through='announce.Solicitation', to='core.influenceur'),
        ),
    ]
