# Generated by Django 4.1.3 on 2022-12-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0003_remove_solicitation_user_solicitation_influenceur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
