# Generated by Django 4.1.3 on 2022-12-01 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announce', '0002_announce_cover'),
        ('core', '0005_pays_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='contrat')),
                ('send_notification', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announce.announce')),
                ('destinataires', models.ManyToManyField(to='core.influenceur')),
            ],
        ),
    ]
